run:
  skip-dirs-use-default: false

linters:
  enable-all: true
  disable:
    - gochecknoinits
    - paralleltest
    - wrapcheck
    - gosec
    - gochecknoglobals
    - musttag
    - wsl
    - gocritic
    - varnamelen
    - forbidigo
    - lll
    - revive
    - gomnd
    - nlreturn
    - exhaustruct
    - nilnil
    - nonamedreturns

    # Deprecated ones:
    - structcheck
    - interfacer
    - deadcode
    - varcheck
    - ifshort
    - exhaustivestruct
    - golint
    - maligned
    - nosnakecase
    - scopelint

gocyclo:
  min-complexity: 15

issues:
  exclude-use-default: false
