linters:
  enable-all: true
  disable:
    - depguard
    - gochecknoinits
    - paralleltest
    - wrapcheck
    - gosec
    - gochecknoglobals
    - musttag
    - wsl
    - gocritic
    - varnamelen
    - forbidigo
    - lll
    - revive
    - gomnd
    - nlreturn
    - exhaustruct
    - nilnil
    - nonamedreturns
    - mnd

    # Deprecated ones:
    - copyloopvar
    - intrange
    - execinquery
    - structcheck
    - interfacer
    - deadcode
    - varcheck
    - ifshort
    - exhaustivestruct
    - golint
    - maligned
    - nosnakecase
    - scopelint

linters-settings:
  gocyclo:
    min-complexity: 15

issues:
  exclude-use-default: false
