name: Rebase l10n_master Daily
on:
  schedule:
    - cron: '31 3 * * *'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rebase l10n_master || true
          git push origin master
          git push -d origin l10n_master || true
